### ISSUE TITLE
POJO

### ISSUE THREAD

**Issue by KenanJones** [KenanJones/POJO-cps206#1]
@anthonykulis
is this the right idea for this lab?
also, I thought gitignore would not let the class files get copied, but it did. do I need to have git desktop for that to work?

**Comment by anthonykulis** [comment]
yeah, your .gitignore looks correct with the `*.class` entry. I am betting you did `git add .` before adding the ignore file. easiest way to fix is manually delete class files and commit. remember that its a stream, and if you add files (`*.class`) at the same time as the ignore or before, the filter isn't available.

**Comment by anthonykulis** [comment]
i wrote a bunch of comments to your commit ca508d19dc1428267bb2e5de85647751fe5e5047

**Comment by KenanJones** [comment]
@anthonykulis 
I have introduced several final variables and packaged everything, how is it looking now?
I will add unit tests once we cover them, I looked them up, but I don't know exactly what to do.

**Comment by anthonykulis** [comment]
i do not see anything at all. your last push was 2 days ago. what you can do, to avoid having to use an issue (which this isn't an issue) is tag me in the commit.

`git commit -am '@anthonykulis - hey, does this .....'`

That way, when you push to github, it will catch that and send me a message. closing this issue when done.
